### ISSUE TITLE
Suggestions to Add

### ISSUE THREAD

**Issue by PauloAlmas** [JyeGuru/7dtd-allocs-map-pins#1]
* Add 10 Slots Tool-belt

* Add this too
https://github.com/Prisma501/Allocs-Webmap-for-CPM

**Comment by JyeGuru** [comment]
Hi - thanks for the suggestions. Unfortunately, they go against the simplicity of what I am trying to achieve here. The server I host is only for a few friends and I to play on, and the sole purpose of this modification was to allow everyone to share information on cleared buildings (we play with no loot respawn) and other major POIs (traders) without having to abuse in-game map pins.
As I was the one with thousands of X markers on my map indicating cleared buildings, and I could not find anyone who had made a similar change already, I found a way to make this easier for us. It is public in the event someone would like to build from it.

As for the specific suggestions:
- 10 slot tool belt: This is something that should be fixed in the base code from Alloc. Also, as my group doesn't really use the web inventory, it hasn't even been an issue for us. I was unaware that there were two slots missing, and at a glance I'm not sure if this can be simply fixed with some Javascript edits, or if it would require additional changes in the DLL.
- CPM: Again, something we don't use. The changes I have made should be easily integrated into the `map.js` from that repo, as I only add a couple of functions. Perhaps you would have better luck asking them to incorporate my changes instead.

Hope this helps clear things up.

**Comment by PauloAlmas** [comment]
I tried to Add markers and gives error, any trick , image of 1 mark , can you post ?

**Comment by JyeGuru** [comment]
This feature requires an external JSON API to interact with - such as AWS API Gateway (which is what I use). It does not function without that.

You will need to change the lines https://github.com/JyeGuru/7dtd-allocs-map-pins/blob/7f79fc4057db43feeb1601b8b65329253efc38a3/webserver/poi.html#L5-L6 and https://github.com/JyeGuru/7dtd-allocs-map-pins/blob/7f79fc4057db43feeb1601b8b65329253efc38a3/webserver/js/map.js#L589-L590 to point at the API you are using.

I was not confident in my ability to use a locally-stored JSON file given that it would need to be updated by clients, so I used a feature I was familiar with.
